services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env_sample
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      - ./backend/pipeline.db:/app/pipeline.db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env_sample
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - backend
